### ISSUE TITLE
API使用的是http的，故在预览时需开启 '开发环境不校验域名以及TLS版本'，可结合自身项目更改 .selectarea.js 文件中的API地址；

### ISSUE THREAD

**Issue by FaiChou** [treadpit/wx_selectArea#1]
> API使用的是http的，故在预览时需开启 '开发环境不校验域名以及TLS版本'，可结合自身项目更改 .selectarea.js 文件中的API地址；

http最后如何通过小程序审核？能否将所有城市导入到https

**Comment by treadpit** [comment]
1. http是肯定通过不了的；
2. https的城市数据接口，用第三方会有一定风险，不可控，所以最好是公司自己维护一个省市区地址选择数据库。

**Comment by FaiChou** [comment]
对， 搁到七牛上

**Comment by treadpit** [comment]
@FaiChou 是的，这样可以
