### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by daolou** [treadpit/wx_selectArea#10]
`'areaPicker.showDistrict': false // 默认为省市区三级区域选择`(这里设为false则是不显示区)
设置只显示省市,不显示区的时候有bug啊:
1.  `{{areaPicker.address}}` 的值是空
2.  `getSelectedAreaData` 获取的城市列表信息也是空的
3.  滑动省的时候对应的城市不改变

**Comment by daolou** [comment]
@treadpit 老哥,你试没试,设置不显示区的时候,有问题

**Comment by treadpit** [comment]
看下提交记录哈 ![image](https://user-images.githubusercontent.com/10692855/37696463-9f02f658-2d11-11e8-8c6f-f9271fc1c569.png)

**Comment by daolou** [comment]
@treadpit 
还有一个问题:点击获取城市信息这个方法,
当重新编译后,不滑动,此时处于(安徽省 - 安庆市)这个状态
直接点击获取城市信息,返回的是空

**Comment by treadpit** [comment]
@hello-guoguo 好的，已做处理
