### ISSUE TITLE
使用 https 协议

### ISSUE THREAD

**Issue by sbitpdc** [treadpit/wx_selectArea#11]
现在小程序后台已经不能设置http了，只能设置 https，而https 的证书又无效。建议做一个本地的地区库，速度又快

**Comment by treadpit** [comment]
@sbitpdc 小程序后台一直都只能设置https 哈，本地地区库是不靠谱的，如果有增删地区，则小程序还需发版，成本太高，相关 issue： #1, #2

**Comment by sbitpdc** [comment]
我已经用本地库了
