### ISSUE TITLE
你的这个程序需要http://japi.zto.cn这个接口，但是小程序的接口都需要https

### ISSUE THREAD

**Issue by duqingnian** [treadpit/wx_selectArea#12]
你的这个程序需要http://japi.zto.cn这个接口，但是小程序的接口都需要https

**Comment by treadpit** [comment]
可以看一下相关 issue 的讨论哈，#1，#2 ，因为这个地址数据用第三方的都是不安全的，所以这个项目只是个示例，需要结合自身情况来做
