### ISSUE TITLE
你的请求是http,测试不了啊。有没有https的省市数据地址呢

### ISSUE THREAD

**Issue by fengye12** [treadpit/wx_selectArea#2]

**Comment by treadpit** [comment]
关于HTTPS的接口暂时没有，这个接口是写demo找的网上的公开接口，需要预览可以关闭开发者工具的 **安全域名** 校验，这样就不会校验HTTPS了  #1

**Comment by treadpit** [comment]
@fengye12 关于HTTPS的接口暂时没有，这个接口是写demo找的网上的公开接口，需要预览可以关闭开发者工具的 安全域名 校验，这样就不会校验HTTPS了 #1
